name: Playwright Automation Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Automation Tests in Docker
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ vars.BASE_URL }}
      API_BASE_URL: ${{ vars.API_BASE_URL }}
      DUMMYJSON_API_BASE_URL: ${{ vars.DUMMYJSON_API_BASE_URL }}
      HEADLESS: "true"
      BROWSER: "chromium"
      DEFAULT_TIMEOUT: "10000"
      EXPECT_TIMEOUT: "20000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t automationexercise-tests .

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e BASE_URL="${BASE_URL}" \
            -e API_BASE_URL="${API_BASE_URL}" \
            -e DUMMYJSON_API_BASE_URL="${DUMMYJSON_API_BASE_URL}" \
            -e HEADLESS="${HEADLESS}" \
            -e BROWSER="${BROWSER}" \
            -e DEFAULT_TIMEOUT="${DEFAULT_TIMEOUT}" \
            -e EXPECT_TIMEOUT="${EXPECT_TIMEOUT}" \
            -v "${{ github.workspace }}/allure-results:/app/allure-results" \
            automationexercise-tests \
            pytest -n 2 -q --alluredir=/app/allure-results
          

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/